title: Hi, my name is Joshua Olatunji ğŸ‘‹ğŸ¼
tagline: Joshua Olatunji - Your Trusted Software Architect and Python Django Technical Lead
author: Joshua Olatunji
github_username:  okayjosh

theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-menus
